services:
  - type: web
    name: portfolio
    env: php
    buildCommand: |
      curl -sS https://getcomposer.org/installer | php
      php composer.phar install --optimize-autoloader --no-dev
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan storage:link
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
